/**
 * EMERGE Capital — Prototype v1.8
 * ─────────────────────────────────────────────────────────────
 * File        : emerge/src/app/glossary/page.tsx
 * Route       : /glossary
 * Description : Searchable glossary — 30 investment terms, 5 categories
 * Project     : Morocco's first AI-powered equity crowdfunding platform
 * Operator    : OVERSEE (AMMC-licensed investment bank)
 * Author      : EMERGE Capital / OVERSEE
 * Created     : June 2026
 * Stack       : Next.js 16 · TypeScript · React · Trilingual FR/EN/AR
 * ─────────────────────────────────────────────────────────────
 */
"use client";
import { useState } from "react";
import Link from "next/link";
import { translations, Lang } from "../translations";
import { useLanguage } from "../LanguageContext";

// ─── Types ────────────────────────────────────────────────────────────────────
type Term = {
  id: string;
  term: Record<string, string>;
  definition: Record<string, string>;
  example?: Record<string, string>;
};

type Category = {
  id: string;
  icon: string;
  title: Record<string, string>;
  terms: Term[];
};

// ─── Glossary content ─────────────────────────────────────────────────────────
const categories: Category[] = [
  {
    id: "financials",
    icon: "📊",
    title: { FR: "Finances d'entreprise", EN: "Company financials", AR: "المالية للشركات" },
    terms: [
      {
        id: "revenue",
        term: { FR: "Chiffre d'affaires (CA)", EN: "Revenue", AR: "رقم الأعمال (الإيرادات)" },
        definition: {
          FR: "Le total des ventes réalisées par une entreprise sur une période donnée. C'est la première ligne du compte de résultat — l'argent qui entre avant toute dépense.",
          EN: "The total sales generated by a company over a given period. It is the top line of the income statement — money coming in before any expenses.",
          AR: "إجمالي المبيعات التي حققتها الشركة خلال فترة معينة. وهو أول سطر في قائمة الدخل — المال الوارد قبل أي نفقات.",
        },
        example: {
          FR: "Une startup vendant 1 000 abonnements à 100 MAD/mois génère un CA mensuel de 100 000 MAD.",
          EN: "A startup selling 1,000 subscriptions at MAD 100/month generates monthly revenue of MAD 100,000.",
          AR: "شركة ناشئة تبيع 1,000 اشتراك بـ100 درهم/شهر تحقق إيرادات شهرية قدرها 100,000 درهم.",
        },
      },
      {
        id: "ebitda",
        term: { FR: "EBITDA", EN: "EBITDA", AR: "الأرباح قبل الفوائد والضرائب والاستهلاك" },
        definition: {
          FR: "Mesure du bénéfice d'exploitation d'une entreprise avant les frais financiers et les ajustements comptables. C'est un indicateur de la capacité de l'entreprise à générer du cash à partir de son activité principale.",
          EN: "A measure of a company's operating profit before financing costs and accounting adjustments. It indicates how much cash the business generates from its core activity.",
          AR: "مقياس لأرباح تشغيل الشركة قبل تكاليف التمويل والتعديلات المحاسبية. يُشير إلى مقدار النقد الذي تولّده الشركة من نشاطها الأساسي.",
        },
        example: {
          FR: "Un EBITDA positif signifie que l'activité principale est rentable, même si l'entreprise est encore déficitaire après prise en compte des intérêts et des amortissements.",
          EN: "A positive EBITDA means the core business is profitable, even if the company is still loss-making after interest and depreciation.",
          AR: "EBITDA الإيجابي يعني أن النشاط الأساسي مربح، حتى لو كانت الشركة لا تزال تُسجّل خسائر بعد الفوائد والاستهلاك.",
        },
      },
      {
        id: "netprofit",
        term: { FR: "Résultat net", EN: "Net profit / loss", AR: "صافي الربح / الخسارة" },
        definition: {
          FR: "Ce qu'il reste à l'entreprise après avoir soustrait toutes ses dépenses (coûts, salaires, impôts, intérêts) de ses revenus. Un résultat négatif est une perte.",
          EN: "What remains after subtracting all expenses (costs, salaries, taxes, interest) from revenues. A negative result is a loss.",
          AR: "ما يتبقى بعد طرح جميع النفقات (التكاليف والرواتب والضرائب والفوائد) من الإيرادات. النتيجة السالبة تعني خسارة.",
        },
        example: {
          FR: "Beaucoup de startups en phase de croissance affichent un résultat négatif : elles investissent plus qu'elles ne gagnent pour conquérir le marché.",
          EN: "Many growth-stage startups show a net loss: they invest more than they earn to capture the market.",
          AR: "كثير من الشركات الناشئة في مرحلة النمو تُسجّل خسائر صافية: فهي تستثمر أكثر مما تكسب لاقتحام السوق.",
        },
      },
      {
        id: "premoney",
        term: { FR: "Valorisation pré-money", EN: "Pre-money valuation", AR: "التقييم قبل الاستثمار" },
        definition: {
          FR: "La valeur estimée d'une entreprise AVANT qu'elle reçoive les fonds levés lors d'un tour de financement. C'est le prix auquel les fondateurs évaluent leur société au moment de l'offre.",
          EN: "The estimated value of a company BEFORE it receives the funds raised in a funding round. It is the price at which founders value their company at the time of the offer.",
          AR: "القيمة المُقدَّرة للشركة قبل استلام الأموال المجمعة في جولة التمويل. وهو السعر الذي يُقيّم به المؤسسون شركتهم وقت الطرح.",
        },
        example: {
          FR: "Si une société a une valorisation pré-money de 5,5M MAD et lève 1M MAD, sa valorisation post-money sera de 6,5M MAD.",
          EN: "If a company has a pre-money valuation of MAD 5.5M and raises MAD 1M, its post-money valuation will be MAD 6.5M.",
          AR: "إذا كان تقييم شركة قبل الاستثمار 5.5 مليون درهم وجمعت مليون درهم، فسيكون تقييمها بعد الاستثمار 6.5 مليون درهم.",
        },
      },
      {
        id: "postmoney",
        term: { FR: "Valorisation post-money", EN: "Post-money valuation", AR: "التقييم بعد الاستثمار" },
        definition: {
          FR: "La valeur de l'entreprise APRÈS réception des fonds levés. Elle est égale à la valorisation pré-money plus les fonds levés. C'est sur cette base que se calcule le pourcentage détenu par les investisseurs.",
          EN: "The value of the company AFTER receiving the raised funds. It equals the pre-money valuation plus the funds raised. The investors' ownership percentage is calculated on this basis.",
          AR: "قيمة الشركة بعد استلام الأموال المجمعة. وتساوي التقييم قبل الاستثمار مضافاً إليه الأموال المجمعة. على هذا الأساس تُحسب نسبة ملكية المستثمرين.",
        },
        example: {
          FR: "Valorisation post-money = 5,5M + 1M = 6,5M MAD. Les investisseurs qui ont apporté 1M détiennent 1M/6,5M = 15,4% de la société.",
          EN: "Post-money = 5.5M + 1M = MAD 6.5M. Investors who contributed MAD 1M own 1M/6.5M = 15.4% of the company.",
          AR: "التقييم بعد الاستثمار = 5.5 + 1 = 6.5 مليون درهم. المستثمرون الذين ساهموا بمليون درهم يمتلكون 1/6.5 = 15.4% من الشركة.",
        },
      },
      {
        id: "dilution",
        term: { FR: "Dilution", EN: "Dilution", AR: "التخفيف" },
        definition: {
          FR: "La réduction du pourcentage de détention d'un actionnaire lorsque de nouvelles actions sont émises. Si une société lève de nouveaux fonds, elle émet de nouvelles actions — ce qui réduit mécaniquement la part de chaque actionnaire existant.",
          EN: "The reduction in a shareholder's ownership percentage when new shares are issued. When a company raises new funds, it issues new shares — which mechanically reduces each existing shareholder's stake.",
          AR: "انخفاض نسبة ملكية المساهم عند إصدار أسهم جديدة. عندما تجمع شركة أموالاً جديدة، تُصدر أسهماً جديدة — مما يُخفّض آلياً حصة كل مساهم حالي.",
        },
        example: {
          FR: "Vous détenez 10% d'une société. Lors d'un nouveau tour, de nouvelles actions sont émises. Votre pourcentage peut passer à 8%. Votre investissement ne perd pas de valeur absolue, mais votre part du gâteau est plus petite.",
          EN: "You hold 10% of a company. In a new round, new shares are issued. Your percentage may drop to 8%. Your investment does not lose absolute value, but your slice of the pie is smaller.",
          AR: "تمتلك 10% من شركة. في جولة جديدة، تُصدَر أسهم جديدة. قد تنخفض نسبتك إلى 8%. لا تخسر قيمة مطلقة، لكن حصتك من الكعكة تصبح أصغر.",
        },
      },
    ],
  },
  {
    id: "investment",
    icon: "💡",
    title: { FR: "Bases de l'investissement", EN: "Investment basics", AR: "أساسيات الاستثمار" },
    terms: [
      {
        id: "equity",
        term: { FR: "Capital / Action", EN: "Equity / Share", AR: "أسهم / حصة رأسمالية" },
        definition: {
          FR: "Détenir une action, c'est détenir une fraction de la propriété d'une société. En tant qu'actionnaire, vous avez droit à une part des bénéfices (dividendes) et à une part de la valeur de la société en cas de vente.",
          EN: "Owning a share means owning a fraction of a company. As a shareholder you are entitled to a share of profits (dividends) and a portion of the company's value if it is sold.",
          AR: "امتلاك سهم يعني امتلاك جزء من ملكية الشركة. بوصفك مساهماً، يحق لك الحصول على جزء من الأرباح (توزيعات الأرباح) وجزء من قيمة الشركة عند بيعها.",
        },
      },
      {
        id: "dividend",
        term: { FR: "Dividende", EN: "Dividend", AR: "توزيعات الأرباح" },
        definition: {
          FR: "Une distribution d'une partie des bénéfices d'une société à ses actionnaires. Les startups en croissance distribuent rarement des dividendes : elles réinvestissent leurs bénéfices pour croître. Le retour sur investissement provient alors de la plus-value à la revente.",
          EN: "A distribution of part of a company's profits to its shareholders. Growth-stage startups rarely pay dividends: they reinvest profits to grow. Returns then come from capital gains on exit.",
          AR: "توزيع جزء من أرباح الشركة على مساهميها. نادراً ما تُوزّع الشركات الناشئة في مرحلة النمو أرباحاً، إذ تُعيد استثمار أرباحها للنمو. تأتي العوائد إذاً من مكاسب رأس المال عند الخروج.",
        },
      },
      {
        id: "capitalgain",
        term: { FR: "Plus-value", EN: "Capital gain", AR: "مكسب رأس المال" },
        definition: {
          FR: "Le profit réalisé lorsque vous vendez vos actions à un prix supérieur à celui auquel vous les avez achetées. Pour les investisseurs en crowdfunding, c'est généralement la principale source de retour.",
          EN: "The profit made when you sell your shares at a higher price than you paid. For crowdfunding investors, this is typically the main source of return.",
          AR: "الربح المحقق عند بيع أسهمك بسعر أعلى مما دفعته. بالنسبة لمستثمري التمويل الجماعي، هذا عادةً المصدر الرئيسي للعائد.",
        },
      },
      {
        id: "liquidity",
        term: { FR: "Liquidité / Illiquidité", EN: "Liquidity / Illiquidity", AR: "السيولة / انعدام السيولة" },
        definition: {
          FR: "Un actif liquide peut être vendu rapidement et facilement (ex : action cotée en bourse). Un investissement illiquide, comme une participation dans une startup, ne peut pas être revendu facilement — il faut attendre un acheteur, ce qui peut prendre des années.",
          EN: "A liquid asset can be sold quickly and easily (e.g. a listed stock). An illiquid investment, like a startup stake, cannot be sold easily — you must wait for a buyer, which may take years.",
          AR: "الأصل السائل يمكن بيعه بسرعة وسهولة (مثل سهم مُدرج). الاستثمار غير السائل، كحصة في شركة ناشئة، لا يمكن بيعه بسهولة — يجب الانتظار لإيجاد مشترٍ، وقد يستغرق ذلك سنوات.",
        },
      },
      {
        id: "diversification",
        term: { FR: "Diversification", EN: "Diversification", AR: "التنويع" },
        definition: {
          FR: "Le fait de répartir ses investissements entre plusieurs actifs différents pour réduire le risque global. Si un investissement perd de la valeur, les autres peuvent compenser. Ne mettez jamais tous vos œufs dans le même panier.",
          EN: "Spreading investments across different assets to reduce overall risk. If one investment loses value, others may compensate. Never put all your eggs in one basket.",
          AR: "توزيع الاستثمارات عبر أصول مختلفة للحد من المخاطر الإجمالية. إذا فقد استثمار ما قيمته، قد يُعوّض عنه غيره. لا تضع كل بيضك في سلة واحدة.",
        },
      },
      {
        id: "multiplier",
        term: { FR: "Multiple de retour (ex. 3x)", EN: "Return multiple (e.g. 3x)", AR: "مضاعف العائد (مثلاً 3x)" },
        definition: {
          FR: "Une façon simple d'exprimer le rendement d'un investissement. Un multiple de 3x signifie que pour 1 000 MAD investis, vous récupérez 3 000 MAD à la sortie. C'est une estimation, pas une garantie.",
          EN: "A simple way to express an investment's return. A 3x multiple means that for MAD 1,000 invested, you receive MAD 3,000 at exit. It is an estimate, not a guarantee.",
          AR: "طريقة بسيطة للتعبير عن عائد الاستثمار. مضاعف 3x يعني أنك مقابل 1,000 درهم مستثمر تحصل على 3,000 درهم عند الخروج. هذا تقدير، ليس ضماناً.",
        },
      },
    ],
  },
  {
    id: "types",
    icon: "🔍",
    title: { FR: "Types d'investissement", EN: "Types of investment", AR: "أنواع الاستثمار" },
    terms: [
      {
        id: "crowdfunding",
        term: { FR: "Financement participatif en capital (Crowdfunding)", EN: "Equity crowdfunding", AR: "التمويل الجماعي بالأسهم" },
        definition: {
          FR: "Un mécanisme permettant à un grand nombre de particuliers d'investir collectivement de petites sommes dans des entreprises non cotées, en échange de parts du capital. C'est ce que propose EMERGE.",
          EN: "A mechanism allowing many individuals to collectively invest small amounts in unlisted companies in exchange for equity stakes. This is what EMERGE offers.",
          AR: "آلية تسمح لعدد كبير من الأفراد بالاستثمار الجماعي بمبالغ صغيرة في شركات غير مُدرجة مقابل حصص رأسمالية. هذا ما تُقدّمه EMERGE.",
        },
      },
      {
        id: "pe",
        term: { FR: "Capital-investissement (Private Equity)", EN: "Private equity", AR: "رأس المال الخاص" },
        definition: {
          FR: "L'investissement dans des sociétés non cotées en bourse, généralement réservé à des investisseurs institutionnels ou très fortunés investissant de grandes sommes. EMERGE démocratise l'accès à ce type d'investissement pour les particuliers.",
          EN: "Investment in unlisted companies, typically reserved for institutional investors or very wealthy individuals investing large sums. EMERGE democratises access to this type of investment for individuals.",
          AR: "الاستثمار في الشركات غير المُدرجة، محجوز عادةً للمستثمرين المؤسسيين أو الأثرياء جداً الذين يستثمرون مبالغ كبيرة. تُديمقراطِ EMERGE الوصول إلى هذا النوع من الاستثمار للأفراد.",
        },
      },
      {
        id: "listedshares",
        term: { FR: "Actions cotées en bourse", EN: "Listed / exchange-traded shares", AR: "الأسهم المُدرجة في البورصة" },
        definition: {
          FR: "Des actions de sociétés qui sont négociées sur un marché boursier réglementé (ex : Bourse de Casablanca). Elles peuvent être achetées et vendues à tout moment aux prix du marché. Plus liquides que les participations en crowdfunding.",
          EN: "Shares in companies traded on a regulated stock exchange (e.g. Casablanca Stock Exchange). They can be bought and sold at any time at market prices. More liquid than crowdfunding stakes.",
          AR: "أسهم شركات مُتداولة في بورصة منظّمة (مثل بورصة الدار البيضاء). يمكن شراؤها وبيعها في أي وقت بأسعار السوق. أكثر سيولة من حصص التمويل الجماعي.",
        },
      },
      {
        id: "bonds",
        term: { FR: "Obligations", EN: "Bonds", AR: "السندات" },
        definition: {
          FR: "Un prêt que vous accordez à une société ou à un État, qui s'engage à vous rembourser avec des intérêts. Contrairement aux actions, vous n'êtes pas propriétaire — vous êtes créancier. Généralement moins risqué mais aussi moins rémunérateur.",
          EN: "A loan you grant to a company or government, which commits to repay you with interest. Unlike shares, you are not an owner — you are a creditor. Generally less risky but also less rewarding.",
          AR: "قرض تمنحه لشركة أو حكومة، تلتزم بسداده مع فوائد. على عكس الأسهم، أنت لست مالكاً — بل دائناً. أقل خطورة عموماً لكنه أقل مردودية.",
        },
      },
      {
        id: "funds",
        term: { FR: "Fonds d'investissement (OPCVM)", EN: "Investment funds (UCITS / OPCVM)", AR: "صناديق الاستثمار (أوبكوم)" },
        definition: {
          FR: "Des véhicules qui collectent l'argent de nombreux investisseurs pour l'investir dans un portefeuille diversifié d'actifs (actions, obligations…). Gérés par des professionnels. Les OPCVM sont la forme réglementée courante au Maroc.",
          EN: "Vehicles that pool money from many investors to invest in a diversified portfolio of assets (shares, bonds…). Managed by professionals. UCITS (OPCVM in French) is the common regulated form in Morocco.",
          AR: "أدوات تجمع أموال العديد من المستثمرين للاستثمار في محفظة متنوعة من الأصول (أسهم وسندات...). تُدار من قِبل محترفين. OPCVM هو الشكل التنظيمي الشائع في المغرب.",
        },
      },
      {
        id: "nominee",
        term: { FR: "Nominee (mandataire)", EN: "Nominee structure", AR: "هيكل المُفوَّض (Nominee)" },
        definition: {
          FR: "Sur EMERGE, vos actions sont détenues par EMERGE Participations en votre nom. Cela signifie qu'EMERGE Participations apparaît comme actionnaire sur le registre officiel de la société, mais vous êtes le vrai bénéficiaire économique. Ce mécanisme permet de gérer des centaines d'investisseurs de manière simple et sécurisée.",
          EN: "On EMERGE, your shares are held by EMERGE Participations on your behalf. EMERGE Participations appears as the shareholder on the company's official register, but you are the true economic beneficiary. This mechanism allows hundreds of investors to be managed simply and securely.",
          AR: "على منصة EMERGE، تُحتجز أسهمك من قِبل EMERGE Participations نيابةً عنك. تظهر EMERGE Participations مساهماً في السجل الرسمي للشركة، لكنك أنت المستفيد الاقتصادي الحقيقي. تُتيح هذه الآلية إدارة مئات المستثمرين بشكل بسيط وآمن.",
        },
      },
    ],
  },
  {
    id: "risk",
    icon: "⚠️",
    title: { FR: "Risques & rendements", EN: "Risk & returns", AR: "المخاطر والعوائد" },
    terms: [
      {
        id: "capitalrisk",
        term: { FR: "Risque de perte en capital", EN: "Capital at risk", AR: "مخاطر فقدان رأس المال" },
        definition: {
          FR: "Le risque de perdre tout ou partie de votre investissement. Dans le crowdfunding en capital, ce risque est élevé : de nombreuses startups échouent. N'investissez que l'argent que vous pouvez vous permettre de perdre.",
          EN: "The risk of losing all or part of your investment. In equity crowdfunding this risk is high: many startups fail. Only invest money you can afford to lose.",
          AR: "مخاطر فقدان كل أو جزء من استثمارك. في التمويل الجماعي بالأسهم، هذه المخاطرة عالية: كثير من الشركات الناشئة تفشل. استثمر فقط المال الذي تستطيع تحمّل خسارته.",
        },
      },
      {
        id: "liquidityrisk",
        term: { FR: "Risque de liquidité", EN: "Liquidity risk", AR: "مخاطر السيولة" },
        definition: {
          FR: "Le risque de ne pas pouvoir revendre vos actions quand vous le souhaitez, faute d'acheteur. Une participation dans une startup non cotée peut être impossible à revendre pendant plusieurs années.",
          EN: "The risk of not being able to sell your shares when you want to, due to lack of buyers. A stake in an unlisted startup may be impossible to sell for several years.",
          AR: "مخاطر عدم القدرة على بيع أسهمك وقت رغبتك في ذلك لغياب مشترٍ. قد يكون من المستحيل بيع حصة في شركة ناشئة غير مُدرجة لسنوات عديدة.",
        },
      },
      {
        id: "dilutionrisk",
        term: { FR: "Risque de dilution", EN: "Dilution risk", AR: "مخاطر التخفيف" },
        definition: {
          FR: "Si la société lève des fonds supplémentaires dans le futur, de nouvelles actions seront émises et votre pourcentage de détention sera réduit. Cela ne signifie pas nécessairement que votre investissement perd de la valeur absolue, mais votre part relative dans la société diminue.",
          EN: "If the company raises additional funds in the future, new shares will be issued and your ownership percentage will decrease. This does not necessarily mean your investment loses absolute value, but your relative stake in the company shrinks.",
          AR: "إذا جمعت الشركة أموالاً إضافية مستقبلاً، ستُصدر أسهماً جديدة وستنخفض نسبة ملكيتك. لا يعني ذلك بالضرورة فقدان استثمارك قيمته المطلقة، لكن حصتك النسبية في الشركة تتقلّص.",
        },
      },
      {
        id: "concentrationrisk",
        term: { FR: "Risque de concentration", EN: "Concentration risk", AR: "مخاطر التركيز" },
        definition: {
          FR: "Le risque d'avoir trop d'argent investi dans un seul actif ou une seule société. Si cet investissement échoue, cela peut avoir un impact majeur sur votre patrimoine. Il est recommandé de ne pas investir plus de 10% de votre patrimoine net dans ce type de produits.",
          EN: "The risk of having too much money in a single asset or company. If that investment fails, it can have a major impact on your wealth. It is recommended not to invest more than 10% of your net assets in this type of product.",
          AR: "مخاطر وضع أموال كثيرة في أصل واحد أو شركة واحدة. إذا فشل هذا الاستثمار، قد يُؤثّر تأثيراً كبيراً على ثروتك. يُوصى بعدم استثمار أكثر من 10% من صافي ثروتك في هذا النوع من المنتجات.",
        },
      },
      {
        id: "horizon",
        term: { FR: "Horizon d'investissement", EN: "Investment horizon", AR: "الأفق الزمني للاستثمار" },
        definition: {
          FR: "La durée pendant laquelle vous prévoyez de garder votre investissement avant de pouvoir récupérer votre argent. Pour le crowdfunding en capital, l'horizon est généralement de 5 à 10 ans. N'investissez pas d'argent dont vous pourriez avoir besoin avant cette échéance.",
          EN: "The length of time you expect to hold your investment before recovering your money. For equity crowdfunding, the horizon is typically 5 to 10 years. Do not invest money you may need before that time.",
          AR: "المدة التي تتوقع فيها الاحتفاظ باستثمارك قبل استرداد أموالك. في التمويل الجماعي بالأسهم، الأفق الزمني عادةً 5 إلى 10 سنوات. لا تستثمر المال الذي قد تحتاجه قبل تلك المدة.",
        },
      },
    ],
  },
  {
    id: "emerge",
    icon: "🤖",
    title: { FR: "Comment fonctionne EMERGE", EN: "How EMERGE works", AR: "كيف تعمل EMERGE" },
    terms: [
      {
        id: "aiscore",
        term: { FR: "Score IA EMERGE", EN: "EMERGE AI score", AR: "نقاط الذكاء الاصطناعي EMERGE" },
        definition: {
          FR: "Une évaluation multi-critères générée par les algorithmes d'EMERGE à partir des documents soumis par l'entreprise. Il mesure la maturité, l'opportunité de marché, la chance de succès, le potentiel de rendement, la conformité Charia et l'impact social. Ce n'est pas un conseil en investissement.",
          EN: "A multi-criteria assessment generated by EMERGE's algorithms from the documents submitted by the company. It measures maturity, market opportunity, chance of success, return potential, Sharia compliance and social impact. It is not investment advice.",
          AR: "تقييم متعدد المعايير تُولّده خوارزميات EMERGE من الوثائق المقدمة من الشركة. يقيس النضج وفرصة السوق واحتمالية النجاح وإمكانية العائد والامتثال الشرعي والأثر الاجتماعي. إنه ليس نصيحة استثمارية.",
        },
      },
      {
        id: "duediligence",
        term: { FR: "Due diligence", EN: "Due diligence", AR: "العناية الواجبة" },
        definition: {
          FR: "Le processus de vérification approfondie d'un projet avant son autorisation à lever des fonds. Sur EMERGE, cela inclut l'analyse IA des documents, la vérification par des analystes financiers, la recherche de données publiques et un échange direct avec l'équipe du projet.",
          EN: "The thorough verification process applied to a project before it is authorised to raise funds. On EMERGE this includes AI analysis of documents, verification by financial analysts, public data research and a direct exchange with the project team.",
          AR: "عملية التحقق المعمّق من مشروع قبل الترخيص له بجمع الأموال. على منصة EMERGE، تشمل التحليل الذكي للوثائق والتحقق من قِبل المحللين الماليين والبحث في البيانات العامة والتبادل المباشر مع فريق المشروع.",
        },
      },
      {
        id: "verified",
        term: { FR: "Badge EMERGE Vérifié", EN: "EMERGE Verified badge", AR: "شارة EMERGE الموثّقة" },
        definition: {
          FR: "Un label attribué aux projets qui ont passé avec succès l'ensemble de la due diligence humaine et remplissent les critères les plus exigeants de la plateforme. Il signifie qu'un analyste financier a vérifié le dossier en profondeur.",
          EN: "A label awarded to projects that have successfully passed the full human due diligence process and meet the platform's most demanding criteria. It means a financial analyst has thoroughly verified the file.",
          AR: "علامة تُمنح للمشاريع التي اجتازت بنجاح عملية العناية الواجبة البشرية الكاملة وتستوفي المعايير الأكثر صرامة على المنصة. تعني أن محللاً مالياً قد تحقق من الملف بعمق.",
        },
      },
      {
        id: "pitchfilm",
        term: { FR: "Pitch film", EN: "Pitch film", AR: "فيلم العرض" },
        definition: {
          FR: "Un court film produit par l'entrepreneur à l'aide des outils fournis par EMERGE, présentant son projet de manière engageante. L'entrepreneur est l'auteur du film et en assume la responsabilité. EMERGE vérifie l'exactitude des informations avant publication.",
          EN: "A short film produced by the entrepreneur using the tools provided by EMERGE, presenting their project in an engaging way. The entrepreneur is the author and bears responsibility for it. EMERGE verifies accuracy before publication.",
          AR: "فيلم قصير يُنتجه صاحب المشروع باستخدام الأدوات التي تُوفّرها EMERGE، يُقدّم مشروعه بأسلوب جذّاب. صاحب المشروع هو مؤلف الفيلم ومسؤول عنه. تتحقق EMERGE من دقة المعلومات قبل النشر.",
        },
      },
      {
        id: "ammc",
        term: { FR: "AMMC", EN: "AMMC", AR: "هيئة مسالك رأس المال المغربية (AMMC)" },
        definition: {
          FR: "L'Autorité Marocaine du Marché des Capitaux — le régulateur des marchés financiers au Maroc. EMERGE opère sous son cadre réglementaire de financement participatif en capital, ce qui garantit la supervision et la protection des investisseurs.",
          EN: "The Moroccan Capital Markets Authority — the financial markets regulator in Morocco. EMERGE operates under its equity crowdfunding regulatory framework, ensuring oversight and investor protection.",
          AR: "هيئة مسالك رأس المال المغربية — جهة تنظيم الأسواق المالية في المغرب. تعمل EMERGE في إطارها التنظيمي للتمويل الجماعي بالأسهم، مما يضمن الإشراف وحماية المستثمرين.",
        },
      },
    ],
  },
];

// ─── UI labels ────────────────────────────────────────────────────────────────
const ui = {
  back:       { FR: "← Retour à l'accueil",     EN: "← Back to home",          AR: "← العودة إلى الرئيسية" },
  badge:      { FR: "Ressources",                EN: "Resources",               AR: "الموارد" },
  title:      { FR: "Lexique financier",         EN: "Financial glossary",       AR: "القاموس المالي" },
  subtitle:   { FR: "Comprenez les termes clés avant d'investir. Chaque définition est expliquée simplement, avec un exemple concret.", EN: "Understand the key terms before investing. Every definition is explained simply, with a concrete example.", AR: "افهم المصطلحات الرئيسية قبل الاستثمار. كل تعريف مشروح ببساطة مع مثال ملموس." },
  search:     { FR: "Rechercher un terme…",      EN: "Search for a term…",       AR: "البحث عن مصطلح…" },
  example:    { FR: "Exemple",                   EN: "Example",                  AR: "مثال" },
  noResults:  { FR: "Aucun résultat pour",       EN: "No results for",           AR: "لا نتائج لـ" },
  allTerms:   { FR: "Tous les termes",           EN: "All terms",               AR: "جميع المصطلحات" },
};

export default function Glossary() {
  const { lang, setLang } = useLanguage();
  const t = translations[lang];
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("all");

  const flags: Record<string, string> = {
    FR: "/img/flag_fr.png", AR: "/img/flag_ar.png", EN: "/img/flag_en.png",
  };

  const query = search.toLowerCase().trim();

  const filtered = categories.map(cat => ({
    ...cat,
    terms: cat.terms.filter(term => {
      if (activeCategory !== "all" && cat.id !== activeCategory) return false;
      if (!query) return true;
      return (
        term.term[lang]?.toLowerCase().includes(query) ||
        term.definition[lang]?.toLowerCase().includes(query)
      );
    }),
  })).filter(cat => cat.terms.length > 0);

  const totalTerms = categories.reduce((s, c) => s + c.terms.length, 0);

  return (
    <main dir={t.dir} style={{ fontFamily: "'Plus Jakarta Sans', sans-serif", background: "#f8f9fb", color: "#0f1923", fontSize: "15px", minHeight: "100vh" }}>

      <style>{`
        @media (max-width: 768px) {
          .emerge-nav-links { display: none !important; }
          .emerge-hero { padding: 2rem 1rem !important; }
          .emerge-section { padding: 2rem 1rem !important; }
          .emerge-grid-2 { grid-template-columns: 1fr !important; }
          .emerge-grid-3 { grid-template-columns: 1fr !important; }
          .emerge-grid-4 { grid-template-columns: 1fr 1fr !important; }
          .emerge-sidebar { display: none !important; }
          .emerge-builder-grid { grid-template-columns: 1fr !important; }
          .emerge-preview-sticky { position: static !important; top: auto !important; }
          .emerge-campaign-cards { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 480px) {
          .emerge-nav-links { display: none !important; }
          .emerge-grid-2 { grid-template-columns: 1fr !important; }
          .emerge-grid-4 { grid-template-columns: 1fr !important; }
        }
      `}</style>

      {/* NAV */}
      <nav style={{ background: "#0f1923", padding: "0 3rem", display: "flex", justifyContent: "space-between", alignItems: "center", height: "68px", position: "sticky", top: 0, zIndex: 100 }}>
        <img src="/img/logo_emerge_cropped.png" alt="Emerge Capital" width={70} style={{ height: "auto", objectFit: "contain" }} />
                <div className="emerge-nav-links" style={{ display: "flex", gap: "1.5rem", alignItems: "center" }}>
          {([
            { label: lang === "FR" ? "Campagnes" : lang === "AR" ? "الحملات" : "Campaigns", href: "/" },
            { label: lang === "FR" ? "Comment ça marche" : lang === "AR" ? "كيف يعمل" : "How it works", href: "/how-it-works" },
            { label: lang === "FR" ? "Investisseurs" : lang === "AR" ? "المستثمرون" : "Investors", href: "/investor" },
            { label: lang === "FR" ? "Déposer un projet" : lang === "AR" ? "تقديم مشروع" : "Submit a project", href: "/submit" },
          ] as {label:string;href:string}[]).map(({ label, href }) => (
            <Link key={href} href={href} style={{ color: "rgba(255,255,255,0.75)", textDecoration: "none", fontSize: "0.82rem", fontWeight: 500, whiteSpace: "nowrap" }}>{label}</Link>
          ))}
        </div>
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          {(["FR", "AR", "EN"] as const).filter(l => l !== lang).map(l => (
            <button key={l} onClick={() => setLang(l)} style={{ background: "none", border: "none", cursor: "pointer", padding: 0 }}>
              <img src={flags[l]} alt={l} width={32} height={22} style={{ borderRadius: "4px", display: "block" }} />
            </button>
          ))}
        </div>
      </nav>

      {/* HERO */}
      <section style={{ background: "#fff", borderBottom: "1px solid #e8ecf0", padding: "3.5rem 3rem 2.5rem", textAlign: "center" }}>
        <div style={{ display: "inline-flex", alignItems: "center", gap: "6px", background: "#eaf6fb", color: "#2a6a8a", padding: "0.4rem 1rem", borderRadius: "100px", fontSize: "0.78rem", fontWeight: 600, marginBottom: "1rem", border: "1px solid #c0e4f0" }}>
          <span style={{ width: "7px", height: "7px", background: "#5bbdd4", borderRadius: "50%", display: "inline-block" }} />
          {ui.badge[lang]}
        </div>
        <h1 style={{ fontSize: "2rem", fontWeight: 800, color: "#0f1923", marginBottom: "0.75rem" }}>{ui.title[lang]}</h1>
        <p style={{ fontSize: "0.92rem", color: "#6b7a8d", lineHeight: 1.7, maxWidth: "520px", margin: "0 auto 1.75rem" }}>{ui.subtitle[lang]}</p>

        {/* Search */}
        <div style={{ maxWidth: "480px", margin: "0 auto", position: "relative" }}>
          <span style={{ position: "absolute", left: lang === "AR" ? "auto" : "14px", right: lang === "AR" ? "14px" : "auto", top: "50%", transform: "translateY(-50%)", fontSize: "1rem", pointerEvents: "none" }}>🔍</span>
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder={ui.search[lang]}
            style={{ width: "100%", padding: `0.75rem ${lang === "AR" ? "0.9rem" : "2.5rem"} 0.75rem ${lang === "AR" ? "2.5rem" : "0.9rem"}`, borderRadius: "10px", border: "1.5px solid #e8ecf0", fontSize: "0.88rem", outline: "none", boxSizing: "border-box", background: "#f8f9fb", color: "#0f1923", fontFamily: "inherit" }}
          />
        </div>
      </section>

      {/* CATEGORY FILTERS */}
      <div style={{ background: "#fff", borderBottom: "1px solid #e8ecf0", padding: "1rem 3rem", display: "flex", gap: "0.5rem", flexWrap: "wrap", justifyContent: "center" }}>
        <button onClick={() => setActiveCategory("all")} style={{ padding: "5px 14px", borderRadius: "100px", border: `1.5px solid ${activeCategory === "all" ? "#2a4a7a" : "#e8ecf0"}`, background: activeCategory === "all" ? "#2a4a7a" : "#f8f9fb", color: activeCategory === "all" ? "#fff" : "#4a5568", fontSize: "0.78rem", fontWeight: 600, cursor: "pointer", transition: "all 0.15s" }}>
          📚 {ui.allTerms[lang]} ({totalTerms})
        </button>
        {categories.map(cat => (
          <button key={cat.id} onClick={() => setActiveCategory(cat.id === activeCategory ? "all" : cat.id)}
            style={{ padding: "5px 14px", borderRadius: "100px", border: `1.5px solid ${activeCategory === cat.id ? "#2a4a7a" : "#e8ecf0"}`, background: activeCategory === cat.id ? "#2a4a7a" : "#f8f9fb", color: activeCategory === cat.id ? "#fff" : "#4a5568", fontSize: "0.78rem", fontWeight: 600, cursor: "pointer", transition: "all 0.15s" }}>
            {cat.icon} {cat.title[lang]} ({cat.terms.length})
          </button>
        ))}
      </div>

      {/* CONTENT */}
      <div style={{ maxWidth: "860px", margin: "0 auto", padding: "2.5rem 2rem 5rem" }}>
        {filtered.length === 0 ? (
          <div style={{ textAlign: "center", padding: "4rem", color: "#8a96a3" }}>
            <div style={{ fontSize: "2.5rem", marginBottom: "1rem" }}>🔍</div>
            <p style={{ fontSize: "0.9rem" }}>{ui.noResults[lang]} "<strong>{search}</strong>"</p>
          </div>
        ) : (
          filtered.map(cat => (
            <div key={cat.id} style={{ marginBottom: "2.5rem" }}>
              {/* Category header */}
              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "1.25rem" }}>
                <div style={{ width: "32px", height: "32px", borderRadius: "8px", background: "#eaf6fb", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1rem", flexShrink: 0 }}>{cat.icon}</div>
                <h2 style={{ fontSize: "1rem", fontWeight: 800, color: "#0f1923", margin: 0 }}>{cat.title[lang]}</h2>
                <div style={{ flex: 1, height: "1px", background: "#e8ecf0" }} />
              </div>

              {/* Terms */}
              <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                {cat.terms.map(term => (
                  <TermCard key={term.id} term={term} lang={lang} exampleLabel={ui.example[lang]} />
                ))}
              </div>
            </div>
          ))
        )}
      </div>

      {/* FOOTER */}
      <footer style={{ background: "#0f1923", color: "#8a96a3", textAlign: "center", padding: "1.5rem", fontSize: "0.78rem" }}>
        © 2026 Emerge Capital · Casablanca, Maroc ·{" "}
        <Link href="/legal" style={{ color: "#5bbdd4", textDecoration: "none" }}>{t.footer.legal}</Link> ·{" "}
        <Link href="/privacy" style={{ color: "#5bbdd4", textDecoration: "none" }}>{t.footer.privacy}</Link>
      </footer>
    </main>
  );
}

// ─── Term card with expand/collapse ──────────────────────────────────────────
function TermCard({ term, lang, exampleLabel }: { term: Term; lang: Lang; exampleLabel: string }) {
  const [open, setOpen] = useState(() => {
    if (typeof window !== "undefined") {
      return window.location.hash === `#${term.id}`;
    }
    return false;
  });
  return (
    <div id={term.id} style={{ background: "#fff", border: "1px solid #e8ecf0", borderRadius: "12px", overflow: "hidden", transition: "box-shadow 0.2s", scrollMarginTop: "80px" }}
      onMouseEnter={e => (e.currentTarget.style.boxShadow = "0 2px 12px rgba(0,0,0,0.06)")}
      onMouseLeave={e => (e.currentTarget.style.boxShadow = "none")}>
      <button onClick={() => setOpen(!open)}
        style={{ width: "100%", background: "none", border: "none", cursor: "pointer", padding: "1rem 1.25rem", display: "flex", justifyContent: "space-between", alignItems: "center", textAlign: lang === "AR" ? "right" : "left" }}>
        <span style={{ fontSize: "0.9rem", fontWeight: 700, color: "#0f1923" }}>{term.term[lang]}</span>
        <span style={{ fontSize: "0.75rem", color: "#5bbdd4", fontWeight: 600, flexShrink: 0, marginLeft: lang === "AR" ? 0 : "1rem", marginRight: lang === "AR" ? "1rem" : 0, transition: "transform 0.2s", transform: open ? "rotate(180deg)" : "none" }}>▼</span>
      </button>
      {open && (
        <div style={{ padding: "0 1.25rem 1.1rem", borderTop: "1px solid #f0f2f5" }}>
          <p style={{ fontSize: "0.85rem", color: "#4a5568", lineHeight: 1.75, margin: "0.75rem 0 0" }}>
            {term.definition[lang]}
          </p>
          {term.example && (
            <div style={{ marginTop: "0.75rem", background: "#f8f9fb", borderRadius: "8px", padding: "0.7rem 0.9rem", borderLeft: lang === "AR" ? "none" : "3px solid #5bbdd4", borderRight: lang === "AR" ? "3px solid #5bbdd4" : "none" }}>
              <span style={{ fontSize: "0.72rem", fontWeight: 700, color: "#5bbdd4", textTransform: "uppercase", letterSpacing: "0.06em" }}>{exampleLabel} · </span>
              <span style={{ fontSize: "0.8rem", color: "#6b7a8d", lineHeight: 1.6 }}>{term.example[lang]}</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
